#!/usr/bin/env node
/**
 * Generate Dart contract constants from the OpenAPI document.
 *
 * Required by Phase 00 §3.2. The patient app maps these wire names into
 * clinic_common_models; it does not treat this file as a widget DTO.
 *
 * Deterministic: sorted keys, no timestamps. CI fails if the file is stale.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const repoRoot = fileURLToPath(new URL('../..', import.meta.url));
const openapiPath = join(repoRoot, 'packages/contracts/openapi/openapi.yaml');
const outPath = join(
    repoRoot,
    'packages/flutter/api_client/lib/src/generated/openapi_contract.dart',
);

const document = parse(readFileSync(openapiPath, 'utf8'));
if (!document?.paths || !document?.components?.schemas) {
    console.error('OpenAPI document is missing paths or components.schemas.');
    process.exit(1);
}

const dartString = (value) => `'${String(value).replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;

const paths = [];
for (const [path, item] of Object.entries(document.paths)) {
    for (const [method, operation] of Object.entries(item)) {
        if (!operation || typeof operation !== 'object' || !operation.operationId) {
            continue;
        }
        paths.push({
            path,
            method: method.toUpperCase(),
            operationId: operation.operationId,
        });
    }
}
paths.sort((a, b) => a.operationId.localeCompare(b.operationId));

const errorCodes = document.components.schemas.ErrorCode?.enum;
if (!Array.isArray(errorCodes) || errorCodes.length === 0) {
    console.error('ErrorCode enum is missing from OpenAPI.');
    process.exit(1);
}

const schemaNames = Object.keys(document.components.schemas).sort();

const pathConstants = paths
    .map((p) => `  static const ${p.operationId} = ${dartString(p.path)};`)
    .join('\n');

const operationIdConstants = paths
    .map((p) => `  static const ${p.operationId} = ${dartString(p.operationId)};`)
    .join('\n');

const methodConstants = paths
    .map((p) => `  static const ${p.operationId} = ${dartString(p.method)};`)
    .join('\n');

const errorCodeConstants = errorCodes
    .map((code) => {
        const ident = code
            .toLowerCase()
            .replace(/_([a-z])/g, (_, c) => c.toUpperCase());
        return `  static const ${ident} = ${dartString(code)};`;
    })
    .join('\n');

const errorCodeList = errorCodes.map((code) => dartString(code)).join(', ');
const schemaList = schemaNames.map((name) => dartString(name)).join(',\n    ');
const operationIdList = paths.map((p) => dartString(p.operationId)).join(', ');

const dart = `// GENERATED FILE. Do not edit.
// Source: packages/contracts/openapi/openapi.yaml
//
// Regenerated by: node scripts/contracts/generate-dart.mjs

/// Wire-level OpenAPI constants for the patient mobile client.
library;

abstract final class OpenApiPaths {
${pathConstants}
}

abstract final class OpenApiOperationIds {
${operationIdConstants}

  static const all = <String>[${operationIdList}];
}

abstract final class OpenApiMethods {
${methodConstants}
}

abstract final class OpenApiErrorCodes {
${errorCodeConstants}

  static const all = <String>[${errorCodeList}];
}

abstract final class OpenApiSchemas {
  static const all = <String>[
    ${schemaList}
  ];
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, dart);
console.log(`Wrote ${paths.length} operations to ${outPath}`);
