import type { Locale } from '@clinic/localization';

export const pharmacyStrings = {
  en: {
    workspace: 'Pharmacy verification',
    accountDenied:
      'This signed-in account is not a pharmacy account. Pharmacy onboarding is not available.',
    sessionExpired: 'Your session expired. Sign in again to continue.',
    staleState: 'The server state changed. The current status was refreshed. Nothing was overwritten.',
    manualReview:
      'This request needs a manual review. Another organization is never identified in this message.',
    engineeringDefault:
      'organization_registration_evidence is an ENGINEERING_DEFAULT synthetic requirement. This is not government or license verification.',
    steps: {
      organization: 'Organization',
      branch: 'Initial branch',
      evidence: 'Evidence',
      review: 'Review and submit',
      status: 'Verification status',
    },
    onboarding: {
      title: 'Create your pharmacy organization',
      intro:
        'Enter the organization and the first public branch location that will be stored. Duplicate detection is server-owned. Payment methods and extra branches are not part of this step.',
      legalName: 'Legal name',
      publicName: 'Public name',
      registration: 'Legal registration identifier',
      continue: 'Continue to branch location',
      back: 'Back',
      submit: 'Create organization',
      submitting: 'Creating organization…',
      branchTitle: 'Initial public branch location',
      branchIntro:
        'These fields become the stored public location of the initial branch. There is no map lookup in this version. Country is Egypt.',
      branchPublicName: 'Initial branch public name',
      address: 'Address',
      country: 'Country',
      egypt: 'Egypt',
      latitude: 'Latitude',
      longitude: 'Longitude',
      phone: 'Branch phone',
    },
    verification: {
      title: 'Pharmacy verification',
      openCase: 'Open or resume verification case',
      opening: 'Opening verification case…',
      selectEvidence: 'Choose registration evidence',
      selectedFile: 'Selected file',
      size: 'Size',
      type: 'Type',
      clearFile: 'Clear selected file',
      upload: 'Upload evidence',
      uploading: 'Uploading evidence…',
      scanning: 'Scanning and validating the uploaded file. This is not yet available evidence.',
      quarantined: 'The file is quarantined pending inspection.',
      validating: 'The file is being validated.',
      available: 'Evidence is available (clean). You can submit for review.',
      rejectedUpload: 'The upload was rejected. Choose a new file and try again.',
      completeIsNotAvailable: 'Upload complete is not the same as available evidence.',
      submit: 'Submit for review',
      submitting: 'Submitting…',
      refresh: 'Refresh status',
      newCase: 'Start a new verification case',
      disabledUntilAvailable: 'Submit stays disabled until the server marks evidence available and clean.',
      requirement: 'Requirement',
      noOperationalNav:
        'Inventory, POS, purchasing, and catalog are not available in this phase, including after approval.',
    },
    status: {
      organization: 'Organization verification',
      lifecycle: 'Organization status',
      branch: 'Initial branch status',
      membership: 'Founding membership status',
      case: 'Case status',
      decision: 'Decision',
      reason: 'Reason',
      none: 'None',
      approvedActive: 'The server reports approved and active identity state. This client does not activate anything.',
    },
    errors: {
      generic: 'The request could not be completed.',
      UNAUTHENTICATED: 'The session is no longer valid.',
      PERMISSION_DENIED: 'This account cannot use pharmacy onboarding.',
      NOT_FOUND: 'The requested record is not available.',
      VERSION_CONFLICT: 'The server state changed. Refresh and continue from the current status.',
      STATE_CONFLICT: 'The server state changed. Refresh and continue from the current status.',
      VALIDATION_FAILED: 'The form could not be submitted. Check the highlighted fields.',
      UNSUPPORTED_FILE: 'Choose a PDF, JPEG, or PNG file of at most 20 MiB.',
      FILE_CHANGED: 'The selected file changed after it was chosen. Choose the file again.',
      FILE_MISSING: 'The selected file is no longer available.',
      UPSTREAM_FAILED: 'The operation could not be completed.',
      TIMEOUT: 'The operation took too long.',
    },
  },
  ar: {
    workspace: 'تحقق الصيدلية',
    accountDenied: 'هذا الحساب المسجّل ليس حساب صيدلية. تجهيز الصيدلية غير متاح.',
    sessionExpired: 'انتهت جلستك. سجّل الدخول مرة أخرى للمتابعة.',
    staleState: 'تغيرت حالة الخادم. تم تحديث الحالة الحالية. لم يُكتب فوق أي شيء.',
    manualReview: 'يحتاج هذا الطلب إلى مراجعة يدوية. لا يتم الكشف عن منظمة أخرى في هذه الرسالة.',
    engineeringDefault:
      'organization_registration_evidence متطلب هندسي افتراضي ENGINEERING_DEFAULT. هذا ليس تحققًا حكوميًا أو ترخيصًا.',
    steps: {
      organization: 'المنظمة',
      branch: 'الفرع الأولي',
      evidence: 'الأدلة',
      review: 'المراجعة والإرسال',
      status: 'حالة التحقق',
    },
    onboarding: {
      title: 'إنشاء منظمة الصيدلية',
      intro:
        'أدخل المنظمة وموقع الفرع العام الأول الذي سيُحفظ. اكتشاف التكرار ملك للخادم. طرق الدفع والفروع الإضافية ليست جزءًا من هذه الخطوة.',
      legalName: 'الاسم القانوني',
      publicName: 'الاسم العام',
      registration: 'معرّف التسجيل القانوني',
      continue: 'متابعة إلى موقع الفرع',
      back: 'رجوع',
      submit: 'إنشاء المنظمة',
      submitting: 'جارٍ إنشاء المنظمة…',
      branchTitle: 'موقع الفرع العام الأولي',
      branchIntro:
        'هذه الحقول تصبح الموقع العام المحفوظ للفرع الأولي. لا يوجد بحث خريطة في هذا الإصدار. الدولة هي مصر.',
      branchPublicName: 'الاسم العام للفرع الأولي',
      address: 'العنوان',
      country: 'الدولة',
      egypt: 'مصر',
      latitude: 'خط العرض',
      longitude: 'خط الطول',
      phone: 'هاتف الفرع',
    },
    verification: {
      title: 'تحقق الصيدلية',
      openCase: 'فتح أو استئناف حالة التحقق',
      opening: 'جارٍ فتح حالة التحقق…',
      selectEvidence: 'اختيار دليل التسجيل',
      selectedFile: 'الملف المختار',
      size: 'الحجم',
      type: 'النوع',
      clearFile: 'مسح الملف المختار',
      upload: 'رفع الدليل',
      uploading: 'جارٍ رفع الدليل…',
      scanning: 'جارٍ فحص الملف المرفوع والتحقق منه. هذا ليس دليلًا متاحًا بعد.',
      quarantined: 'الملف في الحجر بانتظار الفحص.',
      validating: 'جارٍ التحقق من الملف.',
      available: 'الدليل متاح (نظيف). يمكنك الإرسال للمراجعة.',
      rejectedUpload: 'رُفض الرفع. اختر ملفًا جديدًا ثم حاول مرة أخرى.',
      completeIsNotAvailable: 'اكتمال الرفع ليس مساويًا لتوفر الدليل.',
      submit: 'إرسال للمراجعة',
      submitting: 'جارٍ الإرسال…',
      refresh: 'تحديث الحالة',
      newCase: 'بدء حالة تحقق جديدة',
      disabledUntilAvailable: 'يبقى الإرسال معطّلًا حتى يعلّم الخادم الدليل متاحًا ونظيفًا.',
      requirement: 'المتطلب',
      noOperationalNav: 'المخزون ونقطة البيع والمشتريات والكتالوج غير متاحة في هذه المرحلة، بما في ذلك بعد الموافقة.',
    },
    status: {
      organization: 'تحقق المنظمة',
      lifecycle: 'حالة المنظمة',
      branch: 'حالة الفرع الأولي',
      membership: 'حالة عضوية المؤسس',
      case: 'حالة الحالة',
      decision: 'القرار',
      reason: 'السبب',
      none: 'لا يوجد',
      approvedActive: 'يُبلغ الخادم عن حالة هوية موافَق عليها ونشطة. هذا العميل لا يفعّل أي شيء.',
    },
    errors: {
      generic: 'تعذر إكمال الطلب.',
      UNAUTHENTICATED: 'الجلسة لم تعد صالحة.',
      PERMISSION_DENIED: 'لا يمكن لهذا الحساب استخدام تجهيز الصيدلية.',
      NOT_FOUND: 'السجل المطلوب غير متاح.',
      VERSION_CONFLICT: 'تغيرت حالة الخادم. حدّث ثم تابع من الحالة الحالية.',
      STATE_CONFLICT: 'تغيرت حالة الخادم. حدّث ثم تابع من الحالة الحالية.',
      VALIDATION_FAILED: 'تعذر إرسال النموذج. راجع الحقول المميَّزة.',
      UNSUPPORTED_FILE: 'اختر ملف PDF أو JPEG أو PNG بحجم 20 ميبيبايت كحد أقصى.',
      FILE_CHANGED: 'تغير الملف المختار بعد اختياره. اختر الملف مرة أخرى.',
      FILE_MISSING: 'الملف المختار لم يعد متاحًا.',
      UPSTREAM_FAILED: 'تعذر إكمال العملية.',
      TIMEOUT: 'استغرقت العملية وقتًا طويلًا.',
    },
  },
} as const;

export type PharmacyStrings = (typeof pharmacyStrings)[Locale];
