import type { Locale } from '@clinic/localization';

export const pharmacyStrings = {
  en: {
    workspace: 'Pharmacy verification',
    accountDenied:
      'This signed-in account is not a pharmacy account. Pharmacy onboarding is not available.',
    sessionExpired: 'Your session expired. Sign in again to continue.',
    staleState: 'The server state changed. The current status was refreshed. Nothing was overwritten.',
    manualReview:
      'This request needs a manual review. Another organization is never identified in this message.',
    engineeringDefault:
      'organization_registration_evidence is an ENGINEERING_DEFAULT synthetic requirement. This is not government or license verification.',
    steps: {
      organization: 'Organization',
      branch: 'Initial branch',
      evidence: 'Evidence',
      review: 'Review and submit',
      status: 'Verification status',
    },
    onboarding: {
      title: 'Create your pharmacy organization',
      intro:
        'Enter the organization and the first public branch location that will be stored. Duplicate detection is server-owned. Payment methods and extra branches are not part of this step.',
      legalName: 'Legal name',
      publicName: 'Public name',
      registration: 'Legal registration identifier',
      continue: 'Continue to branch location',
      back: 'Back',
      submit: 'Create organization',
      submitting: 'Creating organization…',
      branchTitle: 'Initial public branch location',
      branchIntro:
        'These fields become the stored public location of the initial branch. There is no map lookup in this version. Country is Egypt.',
      branchPublicName: 'Initial branch public name',
      address: 'Address',
      country: 'Country',
      egypt: 'Egypt',
      latitude: 'Latitude',
      longitude: 'Longitude',
      phone: 'Branch phone',
    },
    verification: {
      title: 'Pharmacy verification',
      openCase: 'Open or resume verification case',
      opening: 'Opening verification case…',
      selectEvidence: 'Choose registration evidence',
      selectedFile: 'Selected file',
      size: 'Size',
      type: 'Type',
      clearFile: 'Clear selected file',
      upload: 'Upload evidence',
      uploading: 'Uploading evidence…',
      scanning: 'Scanning and validating the uploaded file. This is not yet available evidence.',
      quarantined: 'The file is quarantined pending inspection.',
      validating: 'The file is being validated.',
      available: 'Evidence is available (clean). You can submit for review.',
      rejectedUpload: 'The upload was rejected. Choose a new file and try again.',
      completeIsNotAvailable: 'Upload complete is not the same as available evidence.',
      submit: 'Submit for review',
      submitting: 'Submitting…',
      refresh: 'Refresh status',
      newCase: 'Start a new verification case',
      disabledUntilAvailable: 'Submit stays disabled until the server marks evidence available and clean.',
      requirement: 'Requirement',
      noOperationalNav:
        'Inventory, POS, purchasing, and catalog are not available in this phase, including after approval.',
    },
    status: {
      organization: 'Organization verification',
      lifecycle: 'Organization status',
      branch: 'Initial branch status',
      membership: 'Founding membership status',
      case: 'Case status',
      decision: 'Decision',
      reason: 'Reason',
      none: 'None',
      approvedActive: 'The server reports approved and active identity state. This client does not activate anything.',
    },
    errors: {
      generic: 'The request could not be completed.',
      UNAUTHENTICATED: 'The session is no longer valid.',
      PERMISSION_DENIED: 'This account cannot use pharmacy onboarding.',
      NOT_FOUND: 'The requested record is not available.',
      VERSION_CONFLICT: 'The server state changed. Refresh and continue from the current status.',
      STATE_CONFLICT: 'The server state changed. Refresh and continue from the current status.',
      VALIDATION_FAILED: 'The form could not be submitted. Check the highlighted fields.',
      UNSUPPORTED_FILE: 'Choose a PDF, JPEG, or PNG file of at most 20 MiB.',
      FILE_CHANGED: 'The selected file changed after it was chosen. Choose the file again.',
      FILE_MISSING: 'The selected file is no longer available.',
      UPSTREAM_FAILED: 'The operation could not be completed.',
      TIMEOUT: 'The operation took too long. Server status was refreshed. A retry reuses the same request.',
    },
    practice: {
      nav: 'Branches',
      verificationNav: 'Verification',
      listTitle: 'Pharmacy branches',
      listIntro:
        'Branches you own. Address and coordinates stay on the private detail screen and are not a public listing.',
      empty: 'No pharmacy branches yet. Add a branch to continue.',
      loading: 'Loading pharmacy branches…',
      refresh: 'Refresh branches',
      refreshMemberships: 'Refresh memberships',
      loadMore: 'Load more',
      addBranch: 'Add branch',
      createTitle: 'Add pharmacy branch',
      createIntro:
        'These fields become the stored public location of the additional branch. There is no map lookup. Country is Egypt. Address and coordinates are saved exactly as entered.',
      detailsTitle: 'Branch details',
      publicName: 'Public name',
      address: 'Address',
      addressHint: 'Saved address as entered. There is no geocoding.',
      country: 'Country',
      countryEg: 'Egypt (EG)',
      latitude: 'Latitude',
      longitude: 'Longitude',
      locationHint: 'Saved location as entered. There is no map provider or geocoding.',
      phone: 'Branch or operator phone',
      phoneHint: 'Write-only. The number is not shown after submit and is not stored in this app.',
      phoneRequired: 'Enter a phone number before creating the branch.',
      confirmCoordinates: 'I confirm these coordinates were entered by me and are not inferred.',
      coordinatePreview: 'Local coordinate preview. No map provider is contacted.',
      status: 'Status',
      version: 'Version',
      createdAt: 'Created',
      updatedAt: 'Updated',
      save: 'Save branch',
      saving: 'Saving branch…',
      create: 'Create branch',
      creating: 'Creating branch…',
      retry: 'Retry',
      backToList: 'Back to branches',
      tabDetails: 'Details',
      tabLocation: 'Location',
      tabTeam: 'Team',
      versionConflict:
        'This branch was changed elsewhere. Refresh the latest version before saving again.',
      refreshLatest: 'Refresh latest',
      notAvailable: 'This branch is not available.',
      gated: 'Branch management is available after the server approves this pharmacy organization.',
      inviteTitle: 'Invite a branch operator',
      inviteIntro:
        'Enter a mobile number. The role is branch_operator and cannot be changed. The number is not stored in this app after the invitation is sent. No SMS or email is sent from this screen.',
      fixedRole: 'Role: branch_operator',
      sendInvite: 'Send invitation',
      sendingInvite: 'Sending invitation…',
      inviteSent: 'Invitation pending.',
      inviteAlreadyPending: 'Invitation already pending.',
      membershipsTitle: 'Memberships',
      membershipsEmpty: 'No branch_operator memberships yet.',
      membershipRole: 'Role',
      membershipStatus: 'Status',
      invitedAt: 'Invited',
      acceptedAt: 'Accepted',
      revokedAt: 'Revoked',
      revoke: 'Revoke membership',
      revokeConfirmTitle: 'Revoke this membership?',
      revokeConfirmBody:
        'The membership will be revoked. History is kept. This is not a hard delete.',
      revokeConfirm: 'Revoke',
      revokeCancel: 'Cancel',
      revoking: 'Revoking…',
      roles: {
        branch_operator: 'Branch operator',
      },
      branchStatuses: {
        draft: 'Draft',
        pending: 'Pending',
        active: 'Active',
        suspended: 'Suspended',
        closed: 'Closed',
      },
      membershipStatuses: {
        pending: 'Pending',
        active: 'Active',
        suspended: 'Suspended',
        revoked: 'Revoked',
      },
      invalidCoordinates: 'Enter valid latitude and longitude for Egypt and confirm them before saving.',
      noPhase10:
        'Inventory, POS, purchasing, catalog, alerts, sales, and Pharmacy Home are not available in this phase.',
    },
  },
  ar: {
    workspace: 'تحقق الصيدلية',
    accountDenied: 'هذا الحساب المسجّل ليس حساب صيدلية. تجهيز الصيدلية غير متاح.',
    sessionExpired: 'انتهت جلستك. سجّل الدخول مرة أخرى للمتابعة.',
    staleState: 'تغيرت حالة الخادم. تم تحديث الحالة الحالية. لم يُكتب فوق أي شيء.',
    manualReview: 'يحتاج هذا الطلب إلى مراجعة يدوية. لا يتم الكشف عن منظمة أخرى في هذه الرسالة.',
    engineeringDefault:
      'organization_registration_evidence متطلب هندسي افتراضي ENGINEERING_DEFAULT. هذا ليس تحققًا حكوميًا أو ترخيصًا.',
    steps: {
      organization: 'المنظمة',
      branch: 'الفرع الأولي',
      evidence: 'الأدلة',
      review: 'المراجعة والإرسال',
      status: 'حالة التحقق',
    },
    onboarding: {
      title: 'إنشاء منظمة الصيدلية',
      intro:
        'أدخل المنظمة وموقع الفرع العام الأول الذي سيُحفظ. اكتشاف التكرار ملك للخادم. طرق الدفع والفروع الإضافية ليست جزءًا من هذه الخطوة.',
      legalName: 'الاسم القانوني',
      publicName: 'الاسم العام',
      registration: 'معرّف التسجيل القانوني',
      continue: 'متابعة إلى موقع الفرع',
      back: 'رجوع',
      submit: 'إنشاء المنظمة',
      submitting: 'جارٍ إنشاء المنظمة…',
      branchTitle: 'موقع الفرع العام الأولي',
      branchIntro:
        'هذه الحقول تصبح الموقع العام المحفوظ للفرع الأولي. لا يوجد بحث خريطة في هذا الإصدار. الدولة هي مصر.',
      branchPublicName: 'الاسم العام للفرع الأولي',
      address: 'العنوان',
      country: 'الدولة',
      egypt: 'مصر',
      latitude: 'خط العرض',
      longitude: 'خط الطول',
      phone: 'هاتف الفرع',
    },
    verification: {
      title: 'تحقق الصيدلية',
      openCase: 'فتح أو استئناف حالة التحقق',
      opening: 'جارٍ فتح حالة التحقق…',
      selectEvidence: 'اختيار دليل التسجيل',
      selectedFile: 'الملف المختار',
      size: 'الحجم',
      type: 'النوع',
      clearFile: 'مسح الملف المختار',
      upload: 'رفع الدليل',
      uploading: 'جارٍ رفع الدليل…',
      scanning: 'جارٍ فحص الملف المرفوع والتحقق منه. هذا ليس دليلًا متاحًا بعد.',
      quarantined: 'الملف في الحجر بانتظار الفحص.',
      validating: 'جارٍ التحقق من الملف.',
      available: 'الدليل متاح (نظيف). يمكنك الإرسال للمراجعة.',
      rejectedUpload: 'رُفض الرفع. اختر ملفًا جديدًا ثم حاول مرة أخرى.',
      completeIsNotAvailable: 'اكتمال الرفع ليس مساويًا لتوفر الدليل.',
      submit: 'إرسال للمراجعة',
      submitting: 'جارٍ الإرسال…',
      refresh: 'تحديث الحالة',
      newCase: 'بدء حالة تحقق جديدة',
      disabledUntilAvailable: 'يبقى الإرسال معطّلًا حتى يعلّم الخادم الدليل متاحًا ونظيفًا.',
      requirement: 'المتطلب',
      noOperationalNav: 'المخزون ونقطة البيع والمشتريات والكتالوج غير متاحة في هذه المرحلة، بما في ذلك بعد الموافقة.',
    },
    status: {
      organization: 'تحقق المنظمة',
      lifecycle: 'حالة المنظمة',
      branch: 'حالة الفرع الأولي',
      membership: 'حالة عضوية المؤسس',
      case: 'حالة الحالة',
      decision: 'القرار',
      reason: 'السبب',
      none: 'لا يوجد',
      approvedActive: 'يُبلغ الخادم عن حالة هوية موافَق عليها ونشطة. هذا العميل لا يفعّل أي شيء.',
    },
    errors: {
      generic: 'تعذر إكمال الطلب.',
      UNAUTHENTICATED: 'الجلسة لم تعد صالحة.',
      PERMISSION_DENIED: 'لا يمكن لهذا الحساب استخدام تجهيز الصيدلية.',
      NOT_FOUND: 'السجل المطلوب غير متاح.',
      VERSION_CONFLICT: 'تغيرت حالة الخادم. حدّث ثم تابع من الحالة الحالية.',
      STATE_CONFLICT: 'تغيرت حالة الخادم. حدّث ثم تابع من الحالة الحالية.',
      VALIDATION_FAILED: 'تعذر إرسال النموذج. راجع الحقول المميَّزة.',
      UNSUPPORTED_FILE: 'اختر ملف PDF أو JPEG أو PNG بحجم 20 ميبيبايت كحد أقصى.',
      FILE_CHANGED: 'تغير الملف المختار بعد اختياره. اختر الملف مرة أخرى.',
      FILE_MISSING: 'الملف المختار لم يعد متاحًا.',
      UPSTREAM_FAILED: 'تعذر إكمال العملية.',
      TIMEOUT: 'استغرقت العملية وقتًا طويلًا. تم تحديث حالة الخادم. إعادة المحاولة تعيد استخدام نفس الطلب.',
    },
    practice: {
      nav: 'الفروع',
      verificationNav: 'التحقق',
      listTitle: 'فروع الصيدلية',
      listIntro: 'الفروع التي تملكها. يبقى العنوان والإحداثيات على شاشة التفاصيل الخاصة وليست دليلًا عامًا.',
      empty: 'لا توجد فروع بعد. أضف فرعًا للمتابعة.',
      loading: 'جارٍ تحميل فروع الصيدلية…',
      refresh: 'تحديث الفروع',
      refreshMemberships: 'تحديث العضويات',
      loadMore: 'تحميل المزيد',
      addBranch: 'إضافة فرع',
      createTitle: 'إضافة فرع صيدلية',
      createIntro:
        'هذه الحقول تصبح الموقع العام المحفوظ للفرع الإضافي. لا يوجد بحث خريطة. الدولة هي مصر. يُحفظ العنوان والإحداثيات كما أُدخلت.',
      detailsTitle: 'تفاصيل الفرع',
      publicName: 'الاسم العام',
      address: 'العنوان',
      addressHint: 'العنوان المحفوظ كما أُدخل. لا يوجد ترميز جغرافي.',
      country: 'الدولة',
      countryEg: 'مصر (EG)',
      latitude: 'خط العرض',
      longitude: 'خط الطول',
      locationHint: 'الموقع المحفوظ كما أُدخل. لا يوجد مزود خرائط أو ترميز جغرافي.',
      phone: 'هاتف الفرع أو المشغّل',
      phoneHint: 'للكتابة فقط. لا يُعرض الرقم بعد الإرسال ولا يُحفظ في هذا التطبيق.',
      phoneRequired: 'أدخل رقم هاتف قبل إنشاء الفرع.',
      confirmCoordinates: 'أؤكد أن هذه الإحداثيات أُدخلت بواسطتي وليست مستنتَجة.',
      coordinatePreview: 'معاينة إحداثيات محلية. لا يتم الاتصال بمزود خرائط.',
      status: 'الحالة',
      version: 'الإصدار',
      createdAt: 'أُنشئ',
      updatedAt: 'حُدّث',
      save: 'حفظ الفرع',
      saving: 'جارٍ حفظ الفرع…',
      create: 'إنشاء الفرع',
      creating: 'جارٍ إنشاء الفرع…',
      retry: 'إعادة المحاولة',
      backToList: 'العودة إلى الفروع',
      tabDetails: 'التفاصيل',
      tabLocation: 'الموقع',
      tabTeam: 'الفريق',
      versionConflict: 'تم تغيير هذا الفرع في مكان آخر. حدّث إلى أحدث إصدار قبل الحفظ مرة أخرى.',
      refreshLatest: 'تحديث الأحدث',
      notAvailable: 'هذا الفرع غير متاح.',
      gated: 'إدارة الفروع متاحة بعد أن يوافق الخادم على منظمة الصيدلية.',
      inviteTitle: 'دعوة مشغّل فرع',
      inviteIntro:
        'أدخل رقم هاتف محمول. الدور هو branch_operator ولا يمكن تغييره. لا يُحفظ الرقم في هذا التطبيق بعد إرسال الدعوة. لا تُرسل رسالة قصيرة أو بريد من هذه الشاشة.',
      fixedRole: 'الدور: branch_operator',
      sendInvite: 'إرسال الدعوة',
      sendingInvite: 'جارٍ إرسال الدعوة…',
      inviteSent: 'الدعوة معلّقة.',
      inviteAlreadyPending: 'الدعوة معلّقة بالفعل.',
      membershipsTitle: 'العضويات',
      membershipsEmpty: 'لا توجد عضويات مشغّل فرع بعد.',
      membershipRole: 'الدور',
      membershipStatus: 'الحالة',
      invitedAt: 'دُعي',
      acceptedAt: 'قُبل',
      revokedAt: 'أُلغي',
      revoke: 'إلغاء العضوية',
      revokeConfirmTitle: 'إلغاء هذه العضوية؟',
      revokeConfirmBody: 'ستُلغى العضوية. يُحتفظ بالسجل. هذا ليس حذفًا نهائيًا.',
      revokeConfirm: 'إلغاء',
      revokeCancel: 'تراجع',
      revoking: 'جارٍ الإلغاء…',
      roles: {
        branch_operator: 'مشغّل الفرع',
      },
      branchStatuses: {
        draft: 'مسودة',
        pending: 'معلّق',
        active: 'نشط',
        suspended: 'موقوف',
        closed: 'مغلق',
      },
      membershipStatuses: {
        pending: 'معلّق',
        active: 'نشط',
        suspended: 'موقوف',
        revoked: 'ملغى',
      },
      invalidCoordinates: 'أدخل خط عرض وخط طول صالحين لمصر وأكّدهما قبل الحفظ.',
      noPhase10: 'المخزون ونقطة البيع والمشتريات والكتالوج والتنبيهات والمبيعات والصفحة الرئيسية غير متاحة في هذه المرحلة.',
    },
  },
} as const;

export type PharmacyStrings = (typeof pharmacyStrings)[Locale];

export function pharmacyErrorMessage(locale: Locale, code: string | undefined): string {
  const catalog = pharmacyStrings[locale].errors;
  if (code && code in catalog) {
    return catalog[code as keyof typeof catalog];
  }
  return catalog.generic;
}
