import type { Locale } from '@clinic/localization';

export const doctorStrings = {
  en: {
    workspace: 'Doctor verification',
    accountDenied:
      'This signed-in account is not a doctor account. Doctor onboarding is not available.',
    sessionExpired: 'Your session expired. Sign in again to continue.',
    staleState: 'The server state changed. The current status was refreshed. Nothing was overwritten.',
    manualReview:
      'This request needs a manual review. No other doctor or identity comparison is shown here.',
    engineeringDefault:
      'professional_id is an ENGINEERING_DEFAULT synthetic requirement. This is not government or syndicate verification.',
    loadingProfile: 'Loading doctor profile…',
    loadingSpecialties: 'Loading specialties…',
    specialtiesUnavailable: 'Specialties could not be loaded. Try again.',
    noClinicalNav:
      'Scheduling, queue, appointments, patients, consultations, and medical records are not available in this phase, including after approval.',
    profile: {
      title: 'Your doctor profile',
      displayName: 'Professional display name',
      specialty: 'Specialty',
      verification: 'Verification status',
      publicStatus: 'Public status',
      version: 'Version',
      approved: 'Approved',
      suspended: 'Suspended',
      hidden: 'Hidden',
      listed: 'Listed',
    },
    statuses: {
      draft: 'Draft',
      pending_review: 'Pending review',
      changes_requested: 'Changes requested',
      approved: 'Approved',
      rejected: 'Rejected',
      suspended: 'Suspended',
      none: 'None',
    },
    onboarding: {
      title: 'Create your doctor profile',
      intro:
        'Enter your professional display name and specialty. National ID is used only to submit this form and is not shown afterwards.',
      nationalId: 'National ID',
      displayName: 'Professional display name',
      specialty: 'Specialty',
      specialtyPlaceholder: 'Select a specialty',
      syndicateNumber: 'Syndicate number (optional)',
      submit: 'Create doctor profile',
      submitting: 'Creating doctor profile…',
      retrySpecialties: 'Retry loading specialties',
    },
    verification: {
      title: 'Doctor verification',
      openCase: 'Open or resume verification case',
      opening: 'Opening verification case…',
      selectEvidence: 'Choose professional verification evidence',
      selectedFile: 'Selected file',
      size: 'Size',
      type: 'Type',
      clearFile: 'Clear selected file',
      upload: 'Upload evidence',
      uploading: 'Uploading evidence…',
      requested: 'Upload requested. Evidence is not available yet.',
      uploadingState: 'Uploading the file. Evidence is not available yet.',
      scanning: 'Scanning and validating the uploaded file. This is not yet available evidence.',
      quarantined: 'The file is quarantined pending inspection.',
      validating: 'The file is being validated.',
      available: 'Evidence is available (clean). You can submit for review.',
      rejectedUpload: 'The upload was rejected. Choose a new file and try again.',
      completeIsNotAvailable: 'Upload complete is not the same as available evidence.',
      submit: 'Submit for review',
      submitting: 'Submitting…',
      refresh: 'Refresh status',
      newCase: 'Start a new verification case',
      disabledUntilAvailable: 'Submit stays disabled until the server marks evidence available and clean.',
      retryPoll: 'Retry upload status',
      pollTimedOut: 'Upload status polling stopped. Refresh or retry to continue.',
      requirement: 'Requirement',
      reason: 'Reason',
      case: 'Case status',
    },
    status: {
      approvedActive:
        'The server reports approved doctor verification. This client does not activate clinical capabilities.',
      suspended:
        'The server reports a suspended doctor verification state. Clinical navigation is not available.',
      pending: 'The server reports pending review. Clinical navigation is not available.',
      changesRequested: 'The server requested changes. Open a new case when you are ready to resubmit.',
      rejected: 'The server rejected this case. Open a new case when you are ready to resubmit.',
    },
    errors: {
      generic: 'The request could not be completed.',
      UNAUTHENTICATED: 'The session is no longer valid.',
      PERMISSION_DENIED: 'This account cannot use doctor onboarding.',
      NOT_FOUND: 'The requested record is not available.',
      VERSION_CONFLICT: 'The server state changed. Refresh and continue from the current status.',
      STATE_CONFLICT: 'The server state changed. Refresh and continue from the current status.',
      VALIDATION_FAILED: 'The form could not be submitted. Check the highlighted fields.',
      UNSUPPORTED_FILE: 'Choose a PDF, JPEG, or PNG file of at most 20 MiB.',
      FILE_CHANGED: 'The selected file changed after it was chosen. Choose the file again.',
      FILE_MISSING: 'The selected file is no longer available.',
      UPSTREAM_FAILED: 'The operation could not be completed.',
      TIMEOUT: 'The operation took too long. Server status was refreshed. A retry reuses the same request.',
    },
  },
  ar: {
    workspace: 'تحقق الطبيب',
    accountDenied: 'هذا الحساب المسجّل ليس حساب طبيب. تجهيز الطبيب غير متاح.',
    sessionExpired: 'انتهت جلستك. سجّل الدخول مرة أخرى للمتابعة.',
    staleState: 'تغيرت حالة الخادم. تم تحديث الحالة الحالية. لم يُكتب فوق أي شيء.',
    manualReview: 'يحتاج هذا الطلب إلى مراجعة يدوية. لا يُعرض طبيب آخر أو نتيجة مقارنة هوية هنا.',
    engineeringDefault:
      'professional_id متطلب هندسي افتراضي ENGINEERING_DEFAULT. هذا ليس تحققًا حكوميًا أو نقابيًا.',
    loadingProfile: 'جارٍ تحميل ملف الطبيب…',
    loadingSpecialties: 'جارٍ تحميل التخصصات…',
    specialtiesUnavailable: 'تعذر تحميل التخصصات. حاول مرة أخرى.',
    noClinicalNav:
      'الجدولة والطابور والمواعيد والمرضى والاستشارات والسجلات الطبية غير متاحة في هذه المرحلة، بما في ذلك بعد الموافقة.',
    profile: {
      title: 'ملف الطبيب',
      displayName: 'الاسم المهني الظاهر',
      specialty: 'التخصص',
      verification: 'حالة التحقق',
      publicStatus: 'الحالة العامة',
      version: 'الإصدار',
      approved: 'موافق عليه',
      suspended: 'موقوف',
      hidden: 'مخفي',
      listed: 'مدرج',
    },
    statuses: {
      draft: 'مسودة',
      pending_review: 'بانتظار المراجعة',
      changes_requested: 'مطلوب تعديلات',
      approved: 'موافق عليه',
      rejected: 'مرفوض',
      suspended: 'موقوف',
      none: 'لا يوجد',
    },
    onboarding: {
      title: 'إنشاء ملف الطبيب',
      intro:
        'أدخل الاسم المهني الظاهر والتخصص. يُستخدم الرقم القومي فقط لإرسال هذا النموذج ولا يُعرض بعد ذلك.',
      nationalId: 'الرقم القومي',
      displayName: 'الاسم المهني الظاهر',
      specialty: 'التخصص',
      specialtyPlaceholder: 'اختر تخصصًا',
      syndicateNumber: 'رقم النقابة (اختياري)',
      submit: 'إنشاء ملف الطبيب',
      submitting: 'جارٍ إنشاء ملف الطبيب…',
      retrySpecialties: 'إعادة تحميل التخصصات',
    },
    verification: {
      title: 'تحقق الطبيب',
      openCase: 'فتح أو استئناف حالة التحقق',
      opening: 'جارٍ فتح حالة التحقق…',
      selectEvidence: 'اختيار دليل التحقق المهني',
      selectedFile: 'الملف المختار',
      size: 'الحجم',
      type: 'النوع',
      clearFile: 'مسح الملف المختار',
      upload: 'رفع الدليل',
      uploading: 'جارٍ رفع الدليل…',
      requested: 'تم طلب الرفع. الدليل غير متاح بعد.',
      uploadingState: 'جارٍ رفع الملف. الدليل غير متاح بعد.',
      scanning: 'جارٍ فحص الملف المرفوع والتحقق منه. هذا ليس دليلًا متاحًا بعد.',
      quarantined: 'الملف في الحجر بانتظار الفحص.',
      validating: 'جارٍ التحقق من الملف.',
      available: 'الدليل متاح (نظيف). يمكنك الإرسال للمراجعة.',
      rejectedUpload: 'رُفض الرفع. اختر ملفًا جديدًا ثم حاول مرة أخرى.',
      completeIsNotAvailable: 'اكتمال الرفع ليس مساويًا لتوفر الدليل.',
      submit: 'إرسال للمراجعة',
      submitting: 'جارٍ الإرسال…',
      refresh: 'تحديث الحالة',
      newCase: 'بدء حالة تحقق جديدة',
      disabledUntilAvailable: 'يبقى الإرسال معطّلًا حتى يعلّم الخادم الدليل متاحًا ونظيفًا.',
      retryPoll: 'إعادة محاولة حالة الرفع',
      pollTimedOut: 'توقف استعلام حالة الرفع. حدّث أو أعد المحاولة للمتابعة.',
      requirement: 'المتطلب',
      reason: 'السبب',
      case: 'حالة الحالة',
    },
    status: {
      approvedActive: 'يُبلغ الخادم عن تحقق طبيب موافق عليه. هذا العميل لا يفعّل قدرات سريرية.',
      suspended: 'يُبلغ الخادم عن حالة تحقق موقوفة. التنقل السريري غير متاح.',
      pending: 'يُبلغ الخادم عن انتظار المراجعة. التنقل السريري غير متاح.',
      changesRequested: 'طلب الخادم تعديلات. افتح حالة جديدة عندما تكون جاهزًا لإعادة الإرسال.',
      rejected: 'رفض الخادم هذه الحالة. افتح حالة جديدة عندما تكون جاهزًا لإعادة الإرسال.',
    },
    errors: {
      generic: 'تعذر إكمال الطلب.',
      UNAUTHENTICATED: 'الجلسة لم تعد صالحة.',
      PERMISSION_DENIED: 'لا يمكن لهذا الحساب استخدام تجهيز الطبيب.',
      NOT_FOUND: 'السجل المطلوب غير متاح.',
      VERSION_CONFLICT: 'تغيرت حالة الخادم. حدّث ثم تابع من الحالة الحالية.',
      STATE_CONFLICT: 'تغيرت حالة الخادم. حدّث ثم تابع من الحالة الحالية.',
      VALIDATION_FAILED: 'تعذر إرسال النموذج. راجع الحقول المميَّزة.',
      UNSUPPORTED_FILE: 'اختر ملف PDF أو JPEG أو PNG بحجم 20 ميبيبايت كحد أقصى.',
      FILE_CHANGED: 'تغير الملف المختار بعد اختياره. اختر الملف مرة أخرى.',
      FILE_MISSING: 'الملف المختار لم يعد متاحًا.',
      UPSTREAM_FAILED: 'تعذر إكمال العملية.',
      TIMEOUT: 'استغرقت العملية وقتًا طويلًا. تم تحديث حالة الخادم. إعادة المحاولة تعيد استخدام نفس الطلب.',
    },
  },
} as const;

export type DoctorStrings = (typeof doctorStrings)[Locale];

export function doctorErrorMessage(locale: Locale, code: string | undefined): string {
  const catalog = doctorStrings[locale].errors;
  if (code && code in catalog) {
    return catalog[code as keyof typeof catalog];
  }
  return catalog.generic;
}
